export const CANADA_CITIES = [
  "Abbotsford",
  "Burnaby",
  "Calgary",
  "Chilliwack",
  "Coquitlam",
  "Edmonton",
  "Halifax",
  "Hamilton",
  "Hope",
  "Kitchener",
  "Langley",
  "London",
  "Maple Ridge",
  "Montreal",
  "North Vancouver",
  "Oshawa",
  "Ottawa",
  "Pitt Meadows",
  "Quebec City",
  "Surrey",
  "Toronto",
  "Vancouver",
  "Victoria",
  "West Vancouver",
  "White Rock",
  "Windsor",
  "Winnipeg"
];
